[project]
name = "sqlalchemy-llm-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain[openai]>=1.0.5",
]

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "sqlalchemy>=2.0.44",
]
